<?php

namespace ContainerPBvDhh1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementControllergetEventsApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NOjGaXO.App\Controller\Admin\EvenementController::getEventsApi()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NOjGaXO.App\\Controller\\Admin\\EvenementController::getEventsApi()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\EvenementRepository',
        ]))->withContext('App\\Controller\\Admin\\EvenementController::getEventsApi()', $container);
    }
}
