<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'adresseId' => [parent::class, 'adresseId', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'feedbacks' => [parent::class, 'feedbacks', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imageurl' => [parent::class, 'imageurl', null, 16],
        "\0".parent::class."\0".'motdepasse' => [parent::class, 'motdepasse', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'replies' => [parent::class, 'replies', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'tel' => [parent::class, 'tel', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'adresseId' => [parent::class, 'adresseId', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'feedbacks' => [parent::class, 'feedbacks', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imageurl' => [parent::class, 'imageurl', null, 16],
        'motdepasse' => [parent::class, 'motdepasse', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'replies' => [parent::class, 'replies', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'tel' => [parent::class, 'tel', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
