<?php

namespace ContainerNvkPyEF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VQpLMh7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VQpLMh7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VQpLMh7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\EvenementController::liste' => ['privates', '.service_locator.uaK11Lb.App\\Controller\\Admin\\EvenementController::liste()', 'getEvenementControllerlisteService', true],
            'App\\Controller\\Admin\\EvenementController::ajouter' => ['privates', '.service_locator.kWc6mvO.App\\Controller\\Admin\\EvenementController::ajouter()', 'getEvenementControllerajouterService', true],
            'App\\Controller\\Admin\\EvenementController::edit' => ['privates', '.service_locator.h.6y6Gy.App\\Controller\\Admin\\EvenementController::edit()', 'getEvenementControllereditService', true],
            'App\\Controller\\Admin\\EvenementController::delete' => ['privates', '.service_locator.e5KakHV.App\\Controller\\Admin\\EvenementController::delete()', 'getEvenementControllerdeleteService', true],
            'App\\Controller\\Admin\\ProgrammeController::listeProgrammes' => ['privates', '.service_locator.McSevCd.App\\Controller\\Admin\\ProgrammeController::listeProgrammes()', 'getProgrammeControllerlisteProgrammesService', true],
            'App\\Controller\\Admin\\ProgrammeController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\ProgrammeController::new()', 'getProgrammeControllernewService', true],
            'App\\Controller\\Admin\\ProgrammeController::edit' => ['privates', '.service_locator.BTmbWK6.App\\Controller\\Admin\\ProgrammeController::edit()', 'getProgrammeControllereditService', true],
            'App\\Controller\\Admin\\ProgrammeController::delete' => ['privates', '.service_locator.BTmbWK6.App\\Controller\\Admin\\ProgrammeController::delete()', 'getProgrammeControllerdeleteService', true],
            'App\\Controller\\Admin\\ProgrammeController::generatePdf' => ['privates', '.service_locator.McSevCd.App\\Controller\\Admin\\ProgrammeController::generatePdf()', 'getProgrammeControllergeneratePdfService', true],
            'App\\Controller\\Front\\eventsController::index' => ['privates', '.service_locator.uaK11Lb.App\\Controller\\Front\\eventsController::index()', 'getEventsControllerindexService', true],
            'App\\Controller\\Front\\eventsController::search' => ['privates', '.service_locator.uaK11Lb.App\\Controller\\Front\\eventsController::search()', 'getEventsControllersearchService', true],
            'App\\Controller\\Front\\eventsController::show' => ['privates', '.service_locator.scb.0A3.App\\Controller\\Front\\eventsController::show()', 'getEventsControllershowService', true],
            'App\\Controller\\Front\\feedbackController::index' => ['privates', '.service_locator.dD8aLsL.App\\Controller\\Front\\feedbackController::index()', 'getFeedbackControllerindexService', true],
            'App\\Controller\\Front\\feedbackController::addFeedback' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Front\\feedbackController::addFeedback()', 'getFeedbackControlleraddFeedbackService', true],
            'App\\Controller\\Front\\feedbackController::delete' => ['privates', '.service_locator.aJoVYSb.App\\Controller\\Front\\feedbackController::delete()', 'getFeedbackControllerdeleteService', true],
            'App\\Controller\\Front\\feedbackController::updateFeedback' => ['privates', '.service_locator.aJoVYSb.App\\Controller\\Front\\feedbackController::updateFeedback()', 'getFeedbackControllerupdateFeedbackService', true],
            'App\\Controller\\Front\\feedbackController::createReply' => ['privates', '.service_locator.egipcEH.App\\Controller\\Front\\feedbackController::createReply()', 'getFeedbackControllercreateReplyService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\EvenementController:liste' => ['privates', '.service_locator.uaK11Lb.App\\Controller\\Admin\\EvenementController::liste()', 'getEvenementControllerlisteService', true],
            'App\\Controller\\Admin\\EvenementController:ajouter' => ['privates', '.service_locator.kWc6mvO.App\\Controller\\Admin\\EvenementController::ajouter()', 'getEvenementControllerajouterService', true],
            'App\\Controller\\Admin\\EvenementController:edit' => ['privates', '.service_locator.h.6y6Gy.App\\Controller\\Admin\\EvenementController::edit()', 'getEvenementControllereditService', true],
            'App\\Controller\\Admin\\EvenementController:delete' => ['privates', '.service_locator.e5KakHV.App\\Controller\\Admin\\EvenementController::delete()', 'getEvenementControllerdeleteService', true],
            'App\\Controller\\Admin\\ProgrammeController:listeProgrammes' => ['privates', '.service_locator.McSevCd.App\\Controller\\Admin\\ProgrammeController::listeProgrammes()', 'getProgrammeControllerlisteProgrammesService', true],
            'App\\Controller\\Admin\\ProgrammeController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\ProgrammeController::new()', 'getProgrammeControllernewService', true],
            'App\\Controller\\Admin\\ProgrammeController:edit' => ['privates', '.service_locator.BTmbWK6.App\\Controller\\Admin\\ProgrammeController::edit()', 'getProgrammeControllereditService', true],
            'App\\Controller\\Admin\\ProgrammeController:delete' => ['privates', '.service_locator.BTmbWK6.App\\Controller\\Admin\\ProgrammeController::delete()', 'getProgrammeControllerdeleteService', true],
            'App\\Controller\\Admin\\ProgrammeController:generatePdf' => ['privates', '.service_locator.McSevCd.App\\Controller\\Admin\\ProgrammeController::generatePdf()', 'getProgrammeControllergeneratePdfService', true],
            'App\\Controller\\Front\\eventsController:index' => ['privates', '.service_locator.uaK11Lb.App\\Controller\\Front\\eventsController::index()', 'getEventsControllerindexService', true],
            'App\\Controller\\Front\\eventsController:search' => ['privates', '.service_locator.uaK11Lb.App\\Controller\\Front\\eventsController::search()', 'getEventsControllersearchService', true],
            'App\\Controller\\Front\\eventsController:show' => ['privates', '.service_locator.scb.0A3.App\\Controller\\Front\\eventsController::show()', 'getEventsControllershowService', true],
            'App\\Controller\\Front\\feedbackController:index' => ['privates', '.service_locator.dD8aLsL.App\\Controller\\Front\\feedbackController::index()', 'getFeedbackControllerindexService', true],
            'App\\Controller\\Front\\feedbackController:addFeedback' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Front\\feedbackController::addFeedback()', 'getFeedbackControlleraddFeedbackService', true],
            'App\\Controller\\Front\\feedbackController:delete' => ['privates', '.service_locator.aJoVYSb.App\\Controller\\Front\\feedbackController::delete()', 'getFeedbackControllerdeleteService', true],
            'App\\Controller\\Front\\feedbackController:updateFeedback' => ['privates', '.service_locator.aJoVYSb.App\\Controller\\Front\\feedbackController::updateFeedback()', 'getFeedbackControllerupdateFeedbackService', true],
            'App\\Controller\\Front\\feedbackController:createReply' => ['privates', '.service_locator.egipcEH.App\\Controller\\Front\\feedbackController::createReply()', 'getFeedbackControllercreateReplyService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\EvenementController::liste' => '?',
            'App\\Controller\\Admin\\EvenementController::ajouter' => '?',
            'App\\Controller\\Admin\\EvenementController::edit' => '?',
            'App\\Controller\\Admin\\EvenementController::delete' => '?',
            'App\\Controller\\Admin\\ProgrammeController::listeProgrammes' => '?',
            'App\\Controller\\Admin\\ProgrammeController::new' => '?',
            'App\\Controller\\Admin\\ProgrammeController::edit' => '?',
            'App\\Controller\\Admin\\ProgrammeController::delete' => '?',
            'App\\Controller\\Admin\\ProgrammeController::generatePdf' => '?',
            'App\\Controller\\Front\\eventsController::index' => '?',
            'App\\Controller\\Front\\eventsController::search' => '?',
            'App\\Controller\\Front\\eventsController::show' => '?',
            'App\\Controller\\Front\\feedbackController::index' => '?',
            'App\\Controller\\Front\\feedbackController::addFeedback' => '?',
            'App\\Controller\\Front\\feedbackController::delete' => '?',
            'App\\Controller\\Front\\feedbackController::updateFeedback' => '?',
            'App\\Controller\\Front\\feedbackController::createReply' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\EvenementController:liste' => '?',
            'App\\Controller\\Admin\\EvenementController:ajouter' => '?',
            'App\\Controller\\Admin\\EvenementController:edit' => '?',
            'App\\Controller\\Admin\\EvenementController:delete' => '?',
            'App\\Controller\\Admin\\ProgrammeController:listeProgrammes' => '?',
            'App\\Controller\\Admin\\ProgrammeController:new' => '?',
            'App\\Controller\\Admin\\ProgrammeController:edit' => '?',
            'App\\Controller\\Admin\\ProgrammeController:delete' => '?',
            'App\\Controller\\Admin\\ProgrammeController:generatePdf' => '?',
            'App\\Controller\\Front\\eventsController:index' => '?',
            'App\\Controller\\Front\\eventsController:search' => '?',
            'App\\Controller\\Front\\eventsController:show' => '?',
            'App\\Controller\\Front\\feedbackController:index' => '?',
            'App\\Controller\\Front\\feedbackController:addFeedback' => '?',
            'App\\Controller\\Front\\feedbackController:delete' => '?',
            'App\\Controller\\Front\\feedbackController:updateFeedback' => '?',
            'App\\Controller\\Front\\feedbackController:createReply' => '?',
        ]);
    }
}
