<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPBvDhh1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPBvDhh1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPBvDhh1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPBvDhh1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPBvDhh1\App_KernelDevDebugContainer([
    'container.build_hash' => 'PBvDhh1',
    'container.build_id' => 'edcb9ba6',
    'container.build_time' => 1744894827,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPBvDhh1');
